spring:
  datasource:
    url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 2
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ejb:
          naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
logging:
  level:
    com.laboratory.ms.base.web.RequestLoggingFilter: DEBUG
    com.laboratory.ms.base.web.ResponseLoggingFilter: DEBUG